#!/usr/bin/env php
<?php
/**
 * Entry point for the image storage app
 *
 * PHP version 7.4
 * @author        Ollie Lowson ( @ollielowson )
 */

// Created using PhpStorm

namespace OllieLowson\StorageDemo;

use Dotenv\Dotenv;

// Enable composer PSR-4 autoloading
require __DIR__ . '/../vendor/autoload.php';

// Load environment config
$dotenv = Dotenv::createImmutable(__DIR__ . '/..');
$dotenv->safeLoad();
echo $_ENV['GREETING'] . PHP_EOL;
