#!/usr/bin/env php
<?php
/**
 * Entry point for the image storage app
 *
 * PHP version 7.4
 * @author        Ollie Lowson ( @ollielowson )
 */

// Created using PhpStorm

namespace Ollielowson\StorageDemo;

use Composer\InstalledVersions;
use Ollielowson\StorageDemo\Command\Greet;
use Ollielowson\StorageDemo\Command\StoreImage;
use Symfony\Component\Console\Application;

// Bootstrap the app
require __DIR__ . '/../bootstrap/autoload.php';

// Load Symfony app
$app = new Application('Image Storage Demo', InstalledVersions::getRootPackage()['pretty_version']);

$app->add(new Greet());
$app->add(new StoreImage());

$app->run();
